version: "3.8"

services:

  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./server/uploads:/app/uploads
